Robots:
  - Robot:
      Name: DoosanROS
      ID: 12344
      Address: "10.0.0.23"
      ROSParametes:
      Launchfile:
      OPCUARoboticsFile: RobotUR5.xml
      Skills:
         - MoveToSkill
         - GetStatusSkill
