SAMYCoreConfig:
     AppURI: "AppURItest"
     AppName: "AppNameTest"
     Server:
        Port: 4840
        Encryption: false
        Anonymous: true
        CertificatesPath: ""
     Logging:
        Level:
           App: "info"
           OPCUA: "error"
        Path: "logs"
     ConfigFiles:
        SkillsFile: "/home/felix/Desktop/SAMY/Git/SAMYPlugins/MQTT/samyConfigFiles/Skills.yaml"
        RobotsFile: "/home/felix/Desktop/SAMY/Git/SAMYPlugins/MQTT/samyConfigFiles/RobotsConfiguration.yaml"
        InformationSourcesFile: "/home/felix/Desktop/SAMY/Git/SAMYPlugins/MQTT/samyConfigFiles/InformationSources.yaml"
        DataBaseFile: "/home/felix/Desktop/SAMY/Git/SAMYPlugins/MQTT/samyConfigFiles/DataBaseFile.yaml"
