version: "3.3"

services:
  samycore:
    image: core:latest
    network_mode: "host"
    volumes:
      - ./configFiles:/usr/src/samy/configFiles
  samyros: 
    command: /bin/bash -c './start.sh 127.0.0.1 12345 h2017 virtual'
    image: samyros:latest
    network_mode: "host"
    tty: true
    volumes: 
      - ./configFiles:/usr/src/samy/configFiles
  controller:
    image: controller
    network_mode: "host"
    command: python3 Tests/startBPMNController.py localhost Test_BPMN_no_parallel.diagram BPMNbasedController_Configuration_File.yaml
    tty: true
    volumes:
      - ./configFiles:/usr/src/samy/configFiles

#sed -i -e 's/\r$//' /bin/bash -c 