version: "3.3"

services:
  samycore:
    image: samycore:latest
    network_mode: "host"
    volumes:
      - ./configFiles:/usr/src/samy/configFiles
  samyros: 
    command: /bin/bash -c './start.sh 192.168.61.12 12345 h2017 real'
    image: samyros:latest
    network_mode: "host"
    tty: true
    volumes: 
      - ./configFiles:/usr/src/samy/configFiles
  controller:
    image: controller
    network_mode: "host"
    command: python3 Tests/startBPMNController.py localhost Test_BPMN_no_parallel.diagram BPMNbasedController_Configuration_File.yaml
    tty: true
    volumes:
      - ./configFiles:/usr/src/samy/configFiles

