Robots:
  - Robot:
      Name: OpenMan
      ID: 12344
      Address: "192.168.0.101"
      OPCUARoboticsFile: RobotUR5.xml
      Skills:
        - MoveSkill
        - GripperApproach
        - GripperAttach
        - ToggleGripper
        - GetGripperPose
