Robots:
  - Robot:
      Name: doosan
      ID: 12344
      Address: "10.0.0.20"
      OPCUARoboticsFile: RobotUR5.xml
      Skills:
        - MoveSkill
        - GripperApproach
        - GripperAttach
      Workobject:
        - -0.12
        - -0.4
        - 0.15
        - 0.0
        - 0.0
        - -1.57

